# Generated by Django 3.1.2 on 2020-10-27 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 0, 15, 32, 224082)),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 0, 15, 32, 224082)),
        ),
    ]
