# Generated by Django 3.1.2 on 2020-11-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201104_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddress',
            name='employeeInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeinfo'),
        ),
    ]
