# Generated by Django 3.1.2 on 2020-11-04 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201105_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='employeeAddress',
            field=models.OneToOneField(null=True,default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeaddress'),
            preserve_default=False,
        ),
    ]
