# Generated by Django 3.1.2 on 2020-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeinfo_employeeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='bloodGroup',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], default='a+', max_length=3),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
    ]
