# Generated by Django 3.1.2 on 2020-11-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201105_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddress',
            name='district',
            field=models.CharField(choices=[('barisal', 'Barisal'), ('bhola', 'Bhola'), ('jhalokati', 'Jhalokati'), ('patuakhali', 'Patuakhali'), ('pirojpur', 'Pirojpur'), ('bandarban', 'Bandarban'), ('brahmanbaria', 'Brahmanbaria'), ('chandpur', 'Chandpur'), ('chittagong', 'Chittagong'), ('comilla', 'Comilla'), ('cox-s-bazar', "Cox's Bazar"), ('feni', 'Feni'), ('khagrachhari', 'Khagrachhari'), ('lakshmipur', 'Lakshmipur'), ('noakhali', 'Noakhali'), ('rangamati', 'Rangamati'), ('dhaka', 'Dhaka'), ('faridpur', 'Faridpur'), ('gazipur', 'Gazipur'), ('gopalganj', 'Gopalganj'), ('jamalpur', 'Jamalpur'), ('kishoreganj', 'Kishoreganj'), ('madaripur', 'Madaripur'), ('manikganj', 'Manikganj'), ('munshiganj', 'Munshiganj'), ('mymensingh', 'Mymensingh'), ('narayanganj', 'Narayanganj'), ('narsingdi', 'Narsingdi'), ('netrakona', 'Netrakona'), ('rajbari', 'Rajbari'), ('shariatpur', 'Shariatpur'), ('sherpur', 'Sherpur'), ('tangail', 'Tangail'), ('bagerhat', 'Bagerhat'), ('chuadanga', 'Chuadanga'), ('jessore', 'Jessore'), ('jhenaidah', 'Jhenaidah'), ('khulna', 'Khulna'), ('kushtia', 'Kushtia'), ('magura', 'Magura'), ('meherpur', 'Meherpur'), ('narail', 'Narail'), ('satkhira', 'Satkhira'), ('bogra', 'Bogra'), ('joypurhat', 'Joypurhat'), ('naogaon', 'Naogaon'), ('natore', 'Natore'), ('nawabganj', 'Nawabganj'), ('pabna', 'Pabna'), ('rajshahi', 'Rajshahi'), ('sirajganj', 'Sirajganj'), ('dinajpur', 'Dinajpur'), ('gaibandha', 'Gaibandha'), ('kurigram', 'Kurigram'), ('lalmonirhat', 'Lalmonirhat'), ('nilphamari', 'Nilphamari'), ('panchagarh', 'Panchagarh'), ('rangpur', 'Rangpur'), ('thakurgaon', 'Thakurgaon'), ('habiganj', 'Habiganj'), ('moulvibazar', 'Moulvibazar'), ('sunamganj', 'Sunamganj'), ('Sylhet', 'Sylhet')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='employeeAddress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeaddress', null=True),
        ),
    ]
