# Generated by Django 3.1.2 on 2020-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employeeinfo_employeeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddress',
            name='addressLine2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
